// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafDel_5QH1Rq3wat_MiKIxmJlSXNVn58',
    appId: '1:751073537079:web:a306ffb04b307dd57963b2',
    messagingSenderId: '751073537079',
    projectId: 'mini-project-a17a2',
    authDomain: 'mini-project-a17a2.firebaseapp.com',
    storageBucket: 'mini-project-a17a2.appspot.com',
    measurementId: 'G-49SEV7L0FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv7-RU2MOoe18eQl5X2BmiF5_7hRbTOfE',
    appId: '1:751073537079:android:cea468aff2d9ab147963b2',
    messagingSenderId: '751073537079',
    projectId: 'mini-project-a17a2',
    storageBucket: 'mini-project-a17a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTLYD5iUmmzA3HHgA2fyTtjx4xabwvKDw',
    appId: '1:751073537079:ios:07264eefa3188b057963b2',
    messagingSenderId: '751073537079',
    projectId: 'mini-project-a17a2',
    storageBucket: 'mini-project-a17a2.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );
}
